name: Foreks Data Fetch

on:
  schedule:
    - cron: '0 0 * * *' # Scheduled to run every day at midnight
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements2.txt
    
    - name: Run Python script
      run: python python/foreks_fetch.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update Parquet file" || echo "No changes to commit"
        git push
