name: Main Updater

on:
  schedule:
    - cron: '0 * * * *' # Scheduled to run every day at midnight
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: requirements2.txt
    
    - name: Install dependencies
      run: |
        pip install -r requirements2.txt
    
    - name: Run Python script
      run: python python/midas_main_updater.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update Parquet file" || echo "No changes to commit"
        git push
